2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_setup.py:_flush():76] Configure stats pid to 8385
2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_a', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': 'b4m6o9tu', 'run_id': 'z8gtgo1q', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-b4m6o9tu/config-z8gtgo1q.yaml'}
2022-08-01 15:49:56,881 WARNING Thread-3  :8385 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:49:56,881 INFO    Thread-3  :8385 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_154956-z8gtgo1q/logs/debug.log
2022-08-01 15:49:56,882 INFO    Thread-3  :8385 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_154956-z8gtgo1q/logs/debug-internal.log
2022-08-01 15:49:56,885 INFO    Thread-3  :8385 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:49:56,885 INFO    Thread-3  :8385 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 128, 'IMS_PER_BATCH': 2, 'iteration': 1000, 'learning_rate': 0.0009442600903486468, 'model': None}
config: {}
2022-08-01 15:49:56,889 INFO    Thread-3  :8385 [wandb_init.py:init():548] starting backend
2022-08-01 15:49:56,889 INFO    Thread-3  :8385 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:49:56,906 INFO    Thread-3  :8385 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:49:56,911 INFO    Thread-3  :8385 [backend.py:ensure_launched():222] started backend process with pid: 8416
2022-08-01 15:49:56,912 INFO    Thread-3  :8385 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:49:56,925 INFO    Thread-3  :8385 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 128, 'IMS_PER_BATCH': 2, 'iteration': 1000, 'learning_rate': 0.0009442600903486468, 'model': None}
2022-08-01 15:49:56,928 INFO    Thread-3  :8385 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:49:56,929 INFO    Thread-3  :8385 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:49:57,687 INFO    Thread-3  :8385 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:49:57,732 INFO    Thread-3  :8385 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:49:57,732 INFO    Thread-3  :8385 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:49:58,876 INFO    Thread-3  :8385 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 15:49:58,881 INFO    Thread-3  :8385 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 15:49:58,881 INFO    Thread-3  :8385 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 15:49:58,882 ERROR   Thread-3  :8385 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 15:49:58,884 INFO    Thread-3  :8385 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 15:49:58,887 INFO    Thread-3  :8385 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_a/z8gtgo1q
2022-08-01 15:49:58,887 INFO    Thread-3  :8385 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 15:49:58,888 INFO    Thread-3  :8385 [wandb_run.py:_restore():1834] restore
2022-08-01 15:49:59,200 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 527
}

2022-08-01 15:49:59,639 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:49:59,742 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:49:59,844 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:49:59,960 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:50:00,063 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:50:00,165 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:00,268 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:00,370 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:00,473 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:00,576 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:01,112 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:50:01,645 INFO    Thread-3  :8385 [wandb_run.py:_on_finish():1991] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}
local_info {
}

2022-08-01 15:50:02,784 INFO    Thread-3  :8385 [wandb_run.py:_footer_history_summary_info():3099] rendering history
2022-08-01 15:50:02,784 INFO    Thread-3  :8385 [wandb_run.py:_footer_history_summary_info():3131] rendering summary
2022-08-01 15:50:02,788 INFO    Thread-3  :8385 [wandb_run.py:_footer_sync_info():3055] logging synced files
