2022-08-01 15:53:05,733 INFO    Thread-3  :8592 [wandb_setup.py:_flush():76] Configure stats pid to 8592
2022-08-01 15:53:05,733 INFO    Thread-3  :8592 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 15:53:05,733 INFO    Thread-3  :8592 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 15:53:05,734 INFO    Thread-3  :8592 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_a', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'sweep_id': '1b7bse6h', 'run_id': '20tm57im', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-1b7bse6h/config-20tm57im.yaml'}
2022-08-01 15:53:05,734 WARNING Thread-3  :8592 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 15:53:05,734 INFO    Thread-3  :8592 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 15:53:05,734 INFO    Thread-3  :8592 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155305-20tm57im/logs/debug.log
2022-08-01 15:53:05,734 INFO    Thread-3  :8592 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_155305-20tm57im/logs/debug-internal.log
2022-08-01 15:53:05,738 INFO    Thread-3  :8592 [wandb_init.py:init():495] calling init triggers
2022-08-01 15:53:05,738 INFO    Thread-3  :8592 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 2, 'iteration': 1500, 'learning_rate': 0.0009432121687369956, 'model': None}
config: {}
2022-08-01 15:53:05,741 INFO    Thread-3  :8592 [wandb_init.py:init():548] starting backend
2022-08-01 15:53:05,741 INFO    Thread-3  :8592 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 15:53:05,758 INFO    Thread-3  :8592 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 15:53:05,763 INFO    Thread-3  :8592 [backend.py:ensure_launched():222] started backend process with pid: 8623
2022-08-01 15:53:05,764 INFO    Thread-3  :8592 [wandb_init.py:init():558] backend started and connected
2022-08-01 15:53:05,777 INFO    Thread-3  :8592 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 256, 'IMS_PER_BATCH': 2, 'iteration': 1500, 'learning_rate': 0.0009432121687369956, 'model': None}
2022-08-01 15:53:05,780 INFO    Thread-3  :8592 [wandb_init.py:init():634] updated telemetry
2022-08-01 15:53:05,782 INFO    Thread-3  :8592 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 15:53:06,548 INFO    Thread-3  :8592 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 15:53:06,598 INFO    Thread-3  :8592 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 15:53:06,598 INFO    Thread-3  :8592 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 15:53:07,727 INFO    Thread-3  :8592 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 15:53:07,731 INFO    Thread-3  :8592 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 15:53:07,732 INFO    Thread-3  :8592 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 15:53:07,733 ERROR   Thread-3  :8592 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 15:53:07,735 INFO    Thread-3  :8592 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 15:53:07,737 INFO    Thread-3  :8592 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_a/20tm57im
2022-08-01 15:53:07,737 INFO    Thread-3  :8592 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 15:53:07,738 INFO    Thread-3  :8592 [wandb_run.py:_restore():1834] restore
2022-08-01 15:53:07,952 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  total_bytes: 527
}

2022-08-01 15:53:08,285 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 15:53:08,580 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:53:08,683 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:53:08,786 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:53:08,888 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5911
}

2022-08-01 15:53:08,991 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,093 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,196 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,299 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,401 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,504 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:09,983 INFO    Thread-3  :8592 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5911
  total_bytes: 5911
}

2022-08-01 15:53:10,510 INFO    Thread-3  :8592 [wandb_run.py:_restore():1834] restore
