2022-08-01 18:08:35,172 INFO    Thread-14 :14483 [wandb_setup.py:_flush():76] Configure stats pid to 14483
2022-08-01 18:08:35,172 INFO    Thread-14 :14483 [wandb_setup.py:_flush():76] Loading settings from /home/kana/.config/wandb/settings
2022-08-01 18:08:35,172 INFO    Thread-14 :14483 [wandb_setup.py:_flush():76] Loading settings from wandb/settings
2022-08-01 18:08:35,172 INFO    Thread-14 :14483 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'project': 'noisy_label_cleaning_b', 'entity': 'kka-na', 'root_dir': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script', 'run_id': 'xhwgsumi', 'sweep_param_path': '/home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/sweep-9lkzkcbg/config-xhwgsumi.yaml', 'sweep_id': '9lkzkcbg'}
2022-08-01 18:08:35,172 WARNING Thread-14 :14483 [wandb_setup.py:_flush():76] Could not save program above cwd: ../src/hyp_tuning.py
2022-08-01 18:08:35,172 INFO    Thread-14 :14483 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': None, 'program': '../src/hyp_tuning.py'}
2022-08-01 18:08:35,173 INFO    Thread-14 :14483 [wandb_init.py:_log_setup():461] Logging user logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_180835-xhwgsumi/logs/debug.log
2022-08-01 18:08:35,173 INFO    Thread-14 :14483 [wandb_init.py:_log_setup():462] Logging internal logs to /home/kana/Documents/Training/Reliable_Dataset/cleaning/script/wandb/run-20220801_180835-xhwgsumi/logs/debug-internal.log
2022-08-01 18:08:35,176 INFO    Thread-14 :14483 [wandb_init.py:init():495] calling init triggers
2022-08-01 18:08:35,177 INFO    Thread-14 :14483 [wandb_init.py:init():498] wandb.init called with sweep_config: {'BATCH_SIZE_PER_IMAGE': 64, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0003174681920184259, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
config: {}
2022-08-01 18:08:35,180 INFO    Thread-14 :14483 [wandb_init.py:init():548] starting backend
2022-08-01 18:08:35,180 INFO    Thread-14 :14483 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-08-01 18:08:35,190 INFO    Thread-14 :14483 [backend.py:ensure_launched():217] starting backend process...
2022-08-01 18:08:35,211 INFO    Thread-14 :14483 [backend.py:ensure_launched():222] started backend process with pid: 14824
2022-08-01 18:08:35,212 INFO    Thread-14 :14483 [wandb_init.py:init():558] backend started and connected
2022-08-01 18:08:35,230 INFO    Thread-14 :14483 [wandb_run.py:_config_callback():1131] config_cb None None {'BATCH_SIZE_PER_IMAGE': 64, 'IMS_PER_BATCH': 8, 'iteration': 5000, 'learning_rate': 0.0003174681920184259, 'model': 'COCO-Detection/faster_rcnn_R_101_DC5_3x.yaml'}
2022-08-01 18:08:35,234 INFO    Thread-14 :14483 [wandb_init.py:init():634] updated telemetry
2022-08-01 18:08:35,236 INFO    Thread-14 :14483 [wandb_init.py:init():665] communicating run to backend with 30 second timeout
2022-08-01 18:08:36,071 INFO    Thread-14 :14483 [wandb_run.py:_on_init():1919] communicating current version
2022-08-01 18:08:36,115 INFO    Thread-14 :14483 [wandb_run.py:_on_init():1923] got version response 
2022-08-01 18:08:36,116 INFO    Thread-14 :14483 [wandb_init.py:init():700] starting run threads in backend
2022-08-01 18:08:37,285 INFO    Thread-14 :14483 [wandb_run.py:_console_start():1893] atexit reg
2022-08-01 18:08:37,287 INFO    Thread-14 :14483 [wandb_run.py:_redirect():1766] redirect: SettingsConsole.REDIRECT
2022-08-01 18:08:37,287 INFO    Thread-14 :14483 [wandb_run.py:_redirect():1771] Redirecting console.
2022-08-01 18:08:37,287 ERROR   Thread-14 :14483 [wandb_run.py:_redirect():1830] Failed to redirect.
Traceback (most recent call last):
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1823, in _redirect
    out_redir.install()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 702, in install
    _WSCH.add_fd(self._pipe_read_fd)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 652, in add_fd
    self._register()
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/lib/redirect.py", line 637, in _register
    old_handler = signal.signal(signal.SIGWINCH, lambda *_: None)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
2022-08-01 18:08:37,287 INFO    Thread-14 :14483 [wandb_init.py:init():732] run started, returning control to user process
2022-08-01 18:08:39,305 INFO    Thread-14 :14483 [wandb_run.py:_finish():1680] finishing run kka-na/noisy_label_cleaning_b/xhwgsumi
2022-08-01 18:08:39,305 INFO    Thread-14 :14483 [wandb_run.py:_atexit_cleanup():1862] got exitcode: 1
2022-08-01 18:08:39,305 INFO    Thread-14 :14483 [wandb_run.py:_restore():1834] restore
2022-08-01 18:08:39,311 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 18:08:39,628 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 527
}

2022-08-01 18:08:40,094 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5950
}

2022-08-01 18:08:40,196 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5950
}

2022-08-01 18:08:40,299 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5950
}

2022-08-01 18:08:40,401 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 527
  total_bytes: 5950
}

2022-08-01 18:08:40,504 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5950
  total_bytes: 5950
}

2022-08-01 18:08:40,607 INFO    Thread-14 :14483 [wandb_run.py:_on_finish():1991] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 5950
  total_bytes: 5950
}

2022-08-01 18:08:40,711 INFO    Thread-14 :14483 [wandb_run.py:_restore():1834] restore
