
{}
Traceback (most recent call last):
  File "../src/hyp_tuning.py", line 146, in <module>
    ht.wandb.agent(sweep_id, ht.train(), count=10)
  File "../src/hyp_tuning.py", line 129, in train
    cfg = self.init_cfg(config)
  File "../src/hyp_tuning.py", line 107, in init_cfg
    cfg.merge_from_file(model_zoo.get_config_file(config.model))
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 160, in __getattr__
    return self.__getitem__(key)
  File "/home/kana/yes/envs/detectron2/lib/python3.8/site-packages/wandb/sdk/wandb_config.py", line 128, in __getitem__
    return self._items[key]
KeyError: 'model'